<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Sales Offer</title>
    <style>
        /* Basic styling for the PDF */
        body { font-family: Arial, sans-serif; font-size: 14px; }
        .header { text-align: center; margin-bottom: 20px; }
        .section { margin-bottom: 20px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        table, th, td { border: 1px solid #000; }
        th, td { padding: 8px; text-align: left; }
    </style>
</head>
<body>
<!-- TODO: Customize the final PDF file -->
<div class="header">
    <h1>Sales Offer</h1>
    <p>Offer Date: {{ $offer_date->format('Y-m-d H:i') }}</p>
</div>

<div class="section">
    <h2>Unit Details</h2>
    <p><strong>Unit No:</strong> {{ $unit->unit_no }}</p>
    <p><strong>Unit Type:</strong> {{ $unit->unit_type }}</p>
    <p><strong>Building:</strong> {{ $unit->building->name ?? 'N/A' }}</p>
    <p><strong>Price:</strong> ${{ number_format($unit->price, 2) }}</p>
</div>

@if($notes)
    <div class="section">
        <h2>Notes</h2>
        <p>{{ $notes }}</p>
    </div>
@endif

<div class="section">
    <h2>Payment Plans</h2>
    @foreach($paymentPlans as $plan)
        <h3>{{ $plan->name }}</h3>
        <p><strong>Selling Price:</strong> ${{ number_format($plan->selling_price, 2) }}</p>
        <p><strong>Admin Fee:</strong> ${{ number_format($plan->admin_fee, 2) }}</p>
        <p><strong>EOI:</strong> ${{ number_format($plan->EOI, 2) }}</p>
        @if($plan->installments->count())
            <table>
                <thead>
                <tr>
                    <th>Description</th>
                    <th>Percentage</th>
                    <th>Date</th>
                    <th>Amount</th>
                </tr>
                </thead>
                <tbody>
                @foreach($plan->installments as $installment)
                    <tr>
                        <td>{{ $installment->description }}</td>
                        <td>{{ $installment->percentage }}%</td>
                        <td>{{ \Carbon\Carbon::parse($installment->date)->format('Y-m-d') }}</td>
                        <td>${{ number_format($installment->amount, 2) }}</td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        @endif
    @endforeach
</div>

<div class="section">
    <h2>Generated By</h2>
    <p>{{ $generated_by->name }} ({{ $generated_by->email }})</p>
</div>
</body>
</html>
